### ISSUE TITLE
重新连接bot的时候很卡顿tps掉的特别严重

### ISSUE THREAD

**Issue by xinge4088** [Minecraft-QQBot/Plugin.Spigot#3]
还有机器人缺少重载配置文件的指令，还是我不知道
主要是解决题目的卡顿问题 还有运行的时候也会掉tps 主要是插件问题
版本 QQBot-2.0.4-1.15.jar

**Comment by Lonely-Sails** [comment]
有大佬在重构插件了。以后注意尽量用重启重载机器人插件，否则会有一些奇奇怪怪的 Bug。本人能力有限，没有精力维护那么多仓库，况且我之前也没有学习过 Java，插件我已经尽力了。
